services:
  mudmonkeys:
    build: .
    container_name: mudmonkeys
    restart: unless-stopped
    user: "${UID}:${GID}"
    environment:
      - TZ=Pacific/Auckland
    env_file:
      - ../.env
    volumes:
      - ./public:/var/www/html
      - ./includes:/var/www/includes
      - ./assets:/var/www/html/assets
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.${APP_NAME}-secure.rule=Host(`${APP_DOMAIN}`)  || Host(`www.${APP_DOMAIN}`)
      - traefik.http.routers.${APP_NAME}-secure.entrypoints=websecure
      - traefik.http.routers.${APP_NAME}-secure.middlewares=common@docker



networks:
  web:
    external: true