name: Deploy
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: deploy.docker3.php.nz
          proxy_key: ${{ secrets.PROXY_KEY }}
          proxy_host: sentinel.maffey.com
          proxy_username: githubproxy
          username: mudmonkeys
          key: ${{ secrets.DEPLOY_KEY }}
          script: /home/mudmonkeys/mudmonkeys/deploy.sh

